theme: jekyll-theme-minimal
title: TnT Bombs Podcast
description: the official site
logo: https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/11517001/11517001-1608792413463-e9c79700cd665.jpg
